### ISSUE TITLE
Result page header is missing logo on moblie

### ISSUE THREAD

**Issue by FiedlerJan** [hochschule-darmstadt/einander-helfen#138]
**Describe the bug**
On a mobile device the einander-helfen.org logo is not display in the header.
Is that a bug or is that on purpose?

**To Reproduce**
1. Go to 'https://cai-einander-helfen-staging.fbi.h-da.de/posts?q=&location=&radius=&page=1' with a mobile device
2. The einander-helfen.org logo is not shown

**Expected behavior**
The einander-helfen.org logo is display in the header.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/64203299/86354378-3d0be880-bc69-11ea-969f-cdb34107cc7f.png)

**Desktop (please complete the following information):**
Not used.

**Smartphone (please complete the following information):**
 - Device: OnePlus 6T
 - OS: Android 10
 - Browser Firefox
 - Version 68.9.0

**Additional context**
None

**Comment by BernhardHumm** [comment]
I would think it’s ok (?)

 

 

 

------------------------------------

 

 

Von: JanF [mailto:notifications@github.com] 
Gesendet: Donnerstag, 2. Juli 2020 13:39
An: hochschule-darmstadt/einander-helfen <einander-helfen@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [hochschule-darmstadt/einander-helfen] Result page header is missing logo on moblie (#138)

 

Describe the bug
On a mobile device the einander-helfen.org logo is not display in the header.
Is that a bug or is that on purpose?

To Reproduce
Steps to reproduce the behavior:

1.	Go to 'https://cai-einander-helfen-staging.fbi.h-da.de/posts?q= <https://cai-einander-helfen-staging.fbi.h-da.de/posts?q=&location=&radius=&page=1> &location=&radius=&page=1' with a mobile device
2.	The einander-helfen.org logo is not shown

Expected behavior
The einander-helfen.org logo is display in the header.

Screenshots
 <https://user-images.githubusercontent.com/64203299/86354378-3d0be880-bc69-11ea-969f-cdb34107cc7f.png> 

Desktop (please complete the following information):
Not used.

Smartphone (please complete the following information):

*	Device: OnePlus 6T
*	OS: Android 10
*	Browser Firefox
*	Version 68.9.0

Additional context
None

**Comment by sgrobarek** [comment]
the logo already takes up a lot of space and that was the reason why I hid it in the mobile view.
I agree with Mr Humm.
