### ISSUE TITLE
There are posts other than volunteering work from ehrenamt-hessen.de that get displayed

### ISSUE THREAD

**Issue by MaiThiD** [hochschule-darmstadt/einander-helfen#201]
**Describe the bug**
There are posts other than volunteering work from ehrenamt-hessen.de that get displayed.

**To Reproduce**
1. Go to 'result page'
2. Use the searchbar and look for a event of ehrenamt-hessen.de like 'Health Nugget - Gesundkeit kompakt'
3. See error

**Expected behavior**
Only posts for volunteering work should be found via the search.

**Screenshots**
![image](https://user-images.githubusercontent.com/64202398/101283258-898bbf00-37d9-11eb-801a-2abf84375535.png)
![image](https://user-images.githubusercontent.com/64202398/101283275-9d372580-37d9-11eb-967d-c099e59a7f2f.png)

**Desktop (please complete the following information):**
- OS: Windows 10
- Browser Google Chrome
- Version 87.0.4280.66

**Additional context**
/

**Comment by jonas-hda** [comment]
This is potentially caused by a missing parameter during crawling or by the search result number on ehrenamtsuche-hessen.de decreasing during crawling. as stated during my presentation about crawling, exceeding the valid pagenumbers for a search request on ehrenamtsuche-hessen.de can lead to getting search results from other categories. we will investigate further to see what causes this behaviour and how to address it

**Comment by MaiThiD** [comment]
Issue has been updated

**Comment by jonas-hda** [comment]
The bug is caused by errors on part of the erhenamtssuche-hessen site. #227 mitigates those issues and ensures, that posts that aren't volunteering work will not be crawled
