### ISSUE TITLE
Out of memory scraping

### ISSUE THREAD

**Issue by FiedlerJan** [hochschule-darmstadt/einander-helfen#205]
**Describe the bug**
During the scraping on the staging server the scraping process get's killed due to missing memory.

**To Reproduce**
1. Log in to the staging server
2. Execute the run_etl.sh script

**Expected behavior**
You should never use the full memory.

**Screenshots**
None

**Additional context**
The staging server has only 4GB of RAM. The default usage is 2GB. At about 4-5 tousands posts in the memory, the maximal memory is exceeded.

**Comment by BernhardHumm** [comment]
I have requested more memory for those machines.

However, you should inspect your code. 4-5 thousands posts should only take megabytes, not gigabytes.

 

 

 

Von: JanF <notifications@github.com> 
Gesendet: Donnerstag, 3. Dezember 2020 23:45
An: hochschule-darmstadt/einander-helfen <einander-helfen@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [hochschule-darmstadt/einander-helfen] Out of memory scraping (#205)

 

Describe the bug
During the scraping on the staging server the scraping process get's killed due to missing memory.

To Reproduce
Steps to reproduce the behavior:

1.	Log in to the staging server
2.	Execute the run_etl.sh script

Expected behavior
You should never use the full memory.

Screenshots
None

Additional context
The staging server has only 4GB of RAM. The default usage is 2GB. At about 4-5 tousands posts in the memory, the maximal memory is exceeded.

**Comment by FiedlerJan** [comment]
Reduced maximum memory usage for about 9000 posts from 2GB+ to 335 MB. Elapsed time of the process was 2 hours and 50 minutes.

```
        Command being timed: "python main.py"
        User time (seconds): 3420.14
        System time (seconds): 357.25
        Percent of CPU this job got: 36%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 2:50:17
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 344692
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 0
        Minor (reclaiming a frame) page faults: 120562508
        Voluntary context switches: 840170
        Involuntary context switches: 91432
        Swaps: 0
        File system inputs: 16
        File system outputs: 198319328
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0
```
