### ISSUE TITLE
Unable to see data on result page between page 181 to 220

### ISSUE THREAD

**Issue by MaiThiD** [hochschule-darmstadt/einander-helfen#215]
**Describe the bug**
Currently unable to see data between page 181/182 to 220.

**To Reproduce**
1. Go to 'result page'
2. Click on page '182'

**Expected behavior**
As there are currently over 855 pages in the result page, I expect to be able to view them all.

**Screenshots**
/

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Google Chrome
- Version 87.0.4280.66

**Additional context**
You will be able to see the data in page 181 if you use the pagination, but if you want to use the url or refresh the page at page 181 it shows no data. If you use the Network-Tool from the DevTools it shows that the data is available.

**Comment by FiedlerJan** [comment]
This error appears if the geo_location of a post is null.

![grafik](https://user-images.githubusercontent.com/64203299/101286590-99ac9a00-37eb-11eb-8d17-392f910db047.png)

Currently the frontend needs a geo_location for each post in order to display it on the map. However, it is not possible to determine a geo_location for all posts. Therefore they should not be displayed on the map.
