### ISSUE TITLE
gutetat hamburg and munich have the wrong source

### ISSUE THREAD

**Issue by FiedlerJan** [hochschule-darmstadt/einander-helfen#234]
**Describe the bug**
The posts which are crawled for gutetat hamburg and munich contain the source of gutetat berlin.

**To Reproduce**
1. Go to 'https://cai-einander-helfen-staging.fbi.h-da.de/posts/7778adbe13c3e4063ff98ad5ff6d4ffb?q=&location=20095%20Hamburg%20%28alle%29&radius=&page=1'
2. See the field 'Quelle'

**Expected behavior**
The source for gutetat hamburg and munich should be displayed correctly.

**Additional context**
None

**Comment by BernhardHumm** [comment]
The source string for all Gute-Tat pages (Berlin, Hamburg, Munich) should be: “www.gute-tat.de”

 

 

 

 

Von: JanF <notifications@github.com> 
Gesendet: Freitag, 11. Dezember 2020 00:12
An: hochschule-darmstadt/einander-helfen <einander-helfen@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [hochschule-darmstadt/einander-helfen] gutetat hamburg and munich have the wrong source (#234)

 

Describe the bug
The posts which are crawled for gutetat hamburg and munich contain the source of gutetat berlin.

To Reproduce
Steps to reproduce the behavior:

1.	Go to 'https://cai-einander-helfen-staging.fbi.h-da.de/posts/7778adbe13c3e4063ff98ad5ff6d4ffb?q= <https://cai-einander-helfen-staging.fbi.h-da.de/posts/7778adbe13c3e4063ff98ad5ff6d4ffb?q=&location=20095%20Hamburg%20%28alle%29&radius=&page=1> &location=20095%20Hamburg%20%28alle%29&radius=&page=1'
2.	See the field 'Quelle'

Expected behavior
The source for gutetat hamburg and munich should be displayed correctly.

Additional context
None
