### ISSUE TITLE
Autocomplete user input in the searchbar 

### ISSUE THREAD

**Issue by BaderChouaib** [hochschule-darmstadt/einander-helfen#28]
**Reason (Why?)**
This feature helps the user to search for posts by autocompletting information for tags and posts.

**Solution (What?)**
Initial concepts for autocompletting are at this branch:
https://github.com/hochschule-darmstadt/einander-helfen/tree/feature/28/autocomplete_search
You could work with the v-autocomplete component in vue. However querying elasticsearch content and updating the items autocompleted via this component seems hard.
The initial concept uses a combobox and updates the autocomplete items on keyUp (there might be a much better event trigger) query with the findByWildcard(). 
You could also create your own autcomplete component.
You should also consider how you want to query for tags for autocompletions . Some options are 

Options:
1. Autocomplete results based on tag content for tags-einander-helfen.csv. Autocomplete posts via query based on matching title, categorie or organization
2. Autocomplete tags and posts via query. tags-einander-helfen.csv is only embedded in backend site and its contents are querried by ES. 

**Not doing**
Autocompleting for content that is not tags or posts (title, organization, categories)

**Relation to other Issues**
#21, #22, #10 

**Acceptance criteria**
When searching for content posts data and tags are autocompleted

**Comment by andresesam** [comment]
Hello everyone, here is a little insight into the intermediate status of the frontend.
Currently, the CSV data is read in and processed in our TagService. The labels and corresponding synonyms are suggested as single items in the searchbar. Are there any comments on this? Here are some screenshots

![cafe](https://user-images.githubusercontent.com/39090774/84496719-bdb07800-acad-11ea-9666-dcb4b11242c3.png)
![all](https://user-images.githubusercontent.com/39090774/84496726-bee1a500-acad-11ea-828f-de95ebf19392.png)

Currently, all suggestions are still displayed if no input from the end user has been entered. Are there any preferences regarding a fixed limitation of items? @BernhardHumm

**Comment by BernhardHumm** [comment]
I have the following suggestions:

 

1.       In the search bar display something like “Suche nach Jugendarbeit, Altenpflege, etc.” instead of “Vorschläge”

2.       Start autocompleting after the user entered the first letter (not with 0 letters)

3.       Display up to 10 suggestions, according to a ranking

4.       Use the number of occurences of a tag in all all posts as the basic rank (compute and store during ETL)

5.       Perform a ranking boosting on the client side: 

a.       If the match is at the beginning of the first word (example “Café” below): x 2.0

b.      If the match is at the beginning of a successive word (example “Service Café” below): x 1.0

c.       If the match is in the middle of a word (example “Flüchtlingscafe” below): x 0.5

6.       Also consider what I have already written about synonyms. 

 

 

 

------------------------------------

 

 

Von: andresesam [mailto:notifications@github.com] 
Gesendet: Freitag, 12. Juni 2020 13:11
An: hochschule-darmstadt/einander-helfen <einander-helfen@noreply.github.com>
Cc: Humm, Bernhard, Prof. Dr. <bernhard.humm@h-da.de>; Mention <mention@noreply.github.com>
Betreff: Re: [hochschule-darmstadt/einander-helfen] Autocomplete user input in the searchbar (#28)

 

Hello everyone, here is a little insight into the intermediate status of the frontend.
Currently, the CSV data is read in and processed in our TagService. The labels and corresponding synonyms are suggested as single items in the searchbar. Are there any comments on this? Here are some screenshots

 <https://user-images.githubusercontent.com/39090774/84496719-bdb07800-acad-11ea-9666-dcb4b11242c3.png> 
 <https://user-images.githubusercontent.com/39090774/84496726-bee1a500-acad-11ea-828f-de95ebf19392.png> 

Currently, all suggestions are still displayed if no input from the end user has been entered. Are there any preferences regarding a fixed limitation of items? @BernhardHumm <https://github.com/BernhardHumm>

**Comment by jschurse** [comment]
> 4. Use the number of occurences of a tag in all all posts as the basic rank (compute and store during ETL)

@marvinseith this looks like an ETL job.
