### ISSUE TITLE
Create component for text

### ISSUE THREAD

**Issue by theErikss0n** [hochschule-darmstadt/einander-helfen#294]
**Reason (Why?)**
Currently About, Imprint and Privacy are including ContainerWithContent.scss, which indicates, that we need a component to display text in, which takes the text to be shown as input

**Solution (What?)**
Create a new component.
Maybe we can use slots to insert the markup-content.

**Relation to other Issues**
#286

**Comment by xcaverxiii** [comment]
I don't thing we need a component for this. This is more an issue about css refactoring. See #297.

We have to look about the css. Some css are located in components does not fit the scope of the components and has impact to other component. Also we could create some global css which could also include the ContainerWithContent.scss, so that we don't have to include the file in the specific components.

Furhtermore, we could look about some classed from vuetify which maybe can help remove some unessaray created css.
