### ISSUE TITLE
Result page map

### ISSUE THREAD

**Issue by tobias-hda** [hochschule-darmstadt/einander-helfen#30]
**Reason (Why?)**
The user shall be able to see the locations of the currently listed advertisements on a map on the results page.

**Solution (What?)**
The map is to be created with leaflet, which is a JavaScript library for mobile-friendly interactive maps. The library allows to place markers on the map. A marker shall be placed for each listed advertisement. The lat and lon values are included in the data model of the advertisements. When the user clicks on an advertisement, the map displays only the marker for the active advertisement. The map can be shown or hidden by clicking a button.

**Not doing**

**Relation to other Issues**

**Acceptance criteria**
On the results page there is a map on which the markers for the currently listed advertisements are drawn. The map only shows the respective marker when an advertisement is active (user clicked on an advertisement). The map can be shown or hidden by clicking a button.

**Comment by BernhardHumm** [comment]
Thank you for the detailed issue description which allows commenting.

Here my suggestions:

The map shall be displayed if the search result contains more than one entry (otherwise direct route to detail page).

The map shall display markers for all posts (e.g. in blue)

When hovering over a marker (mouse over), then information about the post is displayed (tooltip)

When clicking on a marker, then the detail page for this post is opened. 

When the user clicks on a search result, then the detail page for this post is opened.

Via a button, the user can toggle between detail view and map view.

When one post is marked (via search result or clicking on a marker), and the user selects the map view, then this post is highlighted with a different colour (e.g., red for marked post, blue for all other posts) (difference to current suggestion in issue description!)

 

 

------------------------------------

 

 

Von: tobias-hda [mailto:notifications@github.com] 
Gesendet: Mittwoch, 10. Juni 2020 16:12
An: hochschule-darmstadt/einander-helfen <einander-helfen@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [hochschule-darmstadt/einander-helfen] Result page map (#30)

 

Reason (Why?)
The user shall be able to see the locations of the currently listed advertisements on a map on the results page.

Solution (What?)
The map is to be created with leaflet, which is a JavaScript library for mobile-friendly interactive maps. The library allows to place markers on the map. A marker shall be placed for each listed advertisement. The lat and lon values are included in the data model of the advertisements. When the user clicks on an advertisement, the map displays only the marker for the active advertisement. The map can be shown or hidden by clicking a button.

Not doing

Relation to other Issues

Acceptance criteria
On the results page there is a map on which the markers for the currently listed advertisements are drawn. The map only shows the respective marker when an advertisement is active (user clicked on an advertisement). The map can be shown or hidden by clicking a button.

**Comment by jschurse** [comment]
Implemented and merged
