### ISSUE TITLE
Color selected post and pin

### ISSUE THREAD

**Issue by FiedlerJan** [hochschule-darmstadt/einander-helfen#39]
**Reason (Why?)**
The user shall always be able to see which post he has selected. This should be reached by coloring the corresponding post and pin on the result page.

**Solution (What?)**
If the user click on a post the background color of the selected post should be colored differently than the other posts. When the user changes from the detail view to the map view, the color of the corresponding pin should also be different from the others. The colors of the Post and Pin should match.

Since the design of the page contains mainly the colors white and a dark blue, the selected Post and Pin should be colored in a lighter blue color. So the pins, which normally have this color, must be colored differently. I would recommend an orange, as this is a complementary colour.

Lighter blue: #006CE8
Orange: #E89400

**Not doing**
Implementing the function to switch from the detail view to map view.

**Relation to other Issues**
None

**Acceptance criteria**
The background color of the selected item on the results page is a light blue, as is the color of the corresponding pin. All other pins should be orange.

**Comment by BernhardHumm** [comment]
I don’t think that the highlight colour of the post and the colour of the pin must necessarily be the same.

About the pins: red (or orange) invokes attention. Therefore, it is not a good idea to mark all pins in orange and the selected one in blue.

The opposite is better: All pins in blue and the selected one in red.

 

For highlighting the selected post use some standard for highlighting list entries, e.g. a grey shadow. 

 

 

------------------------------------

 

Von: JanF [mailto:notifications@github.com] 
Gesendet: Donnerstag, 18. Juni 2020 19:23
An: hochschule-darmstadt/einander-helfen <einander-helfen@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [hochschule-darmstadt/einander-helfen] Color selected post and pin (#39)

 

Reason (Why?)
The user shall always be able to see which post he has selected. This should be reached by coloring the corresponding post and pin on the result page.

Solution (What?)
If the user click on a post the background color of the selected post should be colored differently than the other posts. When the user changes from the detail view to the map view, the color of the corresponding pin should also be different from the others. The colors of the Post and Pin should match.

Since the design of the page contains mainly the colors white and a dark blue, the selected Post and Pin should be colored in a lighter blue color. So the pins, which normally have this color, must be colored differently. I would recommend an orange, as this is a complementary colour.

Lighter blue: #006CE8
Orange: #E89400

Not doing
Implementing the function to switch from the detail view to map view.


Relation to other Issues


Acceptance criteria
The background color of the selected item on the results page is a light blue, as is the color of the corresponding pin. All other pins should be orange.

**Comment by jschurse** [comment]
Implemented and merged:
![grafik](https://user-images.githubusercontent.com/12964877/85440339-3953d400-b58e-11ea-851e-2c29f4ffaefc.png)

**Comment by jschurse** [comment]
> For highlighting the selected post use some standard for highlighting list entries, e.g. a grey shadow.
I overlooked this point @BernhardHumm 

What do you think of a slight blue background for the selected item?
![grafik](https://user-images.githubusercontent.com/12964877/85441786-ca777a80-b58f-11ea-869e-ee997d6f57bd.png)

![grafik](https://user-images.githubusercontent.com/12964877/85441912-e713b280-b58f-11ea-9295-f7ad5eef537a.png)

**Comment by BernhardHumm** [comment]
Yes, fine

 

 

------------------------------------

 

 

Von: jschurse [mailto:notifications@github.com] 
Gesendet: Dienstag, 23. Juni 2020 20:27
An: hochschule-darmstadt/einander-helfen <einander-helfen@noreply.github.com>
Cc: Humm, Bernhard, Prof. Dr. <bernhard.humm@h-da.de>; Mention <mention@noreply.github.com>
Betreff: Re: [hochschule-darmstadt/einander-helfen] Color selected post and pin (#39)

 

For highlighting the selected post use some standard for highlighting list entries, e.g. a grey shadow.

I overlooked this point @BernhardHumm <https://github.com/BernhardHumm> 

What do you think of a slight blue background for the selected item?
 <https://user-images.githubusercontent.com/12964877/85441786-ca777a80-b58f-11ea-869e-ee997d6f57bd.png> 

 <https://user-images.githubusercontent.com/12964877/85441912-e713b280-b58f-11ea-9295-f7ad5eef537a.png>
