### ISSUE TITLE
Map details button and function

### ISSUE THREAD

**Issue by FiedlerJan** [hochschule-darmstadt/einander-helfen#40]
**Reason (Why?)**
On the result page the user shall be able to switch between the detail view and map view to get all information from a post he needs.

**Solution (What?)**
On the results page, the user should be able to switch from the detail view to the map view. If the results page is loaded and no post has been selected before, the map is displayed. In this case, the user should not be able to switch to the detailed view unless he or she selects a post.

The should be able to switch the views with a button. This button should be located in the top right corner of the detail view and map view.

On the map view the button should contain an information icon and a label with the text "Details". The button should only be displayed if a post is selected.

Since in the detail view in the upper right corner is the icon of the associated web page, it must be placed to the right of it. The button should contain a map icon and a label with the text "Karte".

The button with the back arrow, which is currently used for this purpose, gets a new function. It should deselect the currently selected post and switch to the map view.

**Not doing**
Coloring the selected post and pin.

**Relation to other Issues**
None

**Acceptance criteria**
If a post is selected, you can switch from the detail view to the map view of the same post and the other way around. The post gets deselected if you click on the back arrow.

**Comment by BernhardHumm** [comment]
I am not sure whether the suggested back button functionality is intuitive. I would leave it out for the beginning. 

Didn’t we plan to have the toggle button (Karte, Details) on the left side (replacing the current arrow)?

Didn’t we plan on the right side an x button for closing?

 

 

------------------------------------

 

 

Von: JanF [mailto:notifications@github.com] 
Gesendet: Donnerstag, 18. Juni 2020 20:15
An: hochschule-darmstadt/einander-helfen <einander-helfen@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [hochschule-darmstadt/einander-helfen] Map details button and function (#40)

 

Reason (Why?)
On the result page the user shall be able to switch between the detail view and map view to get all information from a post he needs.

Solution (What?)
On the results page, the user should be able to switch from the detail view to the map view. If the results page is loaded and no post has been selected before, the map is displayed. In this case, the user should not be able to switch to the detailed view unless he or she selects a post.

The should be able to switch the views with a button. This button should be located in the top right corner of the detail view and map view.

On the map view the button should contain an information icon and a label with the text "Details". The button should only be displayed if a post is selected.

Since in the detail view in the upper right corner is the icon of the associated web page, it must be placed to the right of it. The button should contain a map icon and a label with the text "Karte".

The button with the back arrow, which is currently used for this purpose, gets a new function. It should deselect the currently selected post and switch to the map view.

Not doing
Coloring the selected post and pin.

Relation to other Issues
None

Acceptance criteria
If a post is selected, you can switch from the detail view to the map view of the same post and the other way around. The post gets deselected if you click on the back arrow.

**Comment by FiedlerJan** [comment]
@BernhardHumm The issue describes the toggle button it is only placed on the right hand side.

What what the x button do? Where is the function of the x button differ to the function of the back button or the function of the toggle button?

**Comment by BernhardHumm** [comment]
I suggest you implement the toggle button only (neither arrow nor x button).

Place it left or right whatever seems more intuitive to you.

 

------------------------------------

 

 

Von: JanF [mailto:notifications@github.com] 
Gesendet: Freitag, 19. Juni 2020 16:34
An: hochschule-darmstadt/einander-helfen <einander-helfen@noreply.github.com>
Cc: Humm, Bernhard, Prof. Dr. <bernhard.humm@h-da.de>; Mention <mention@noreply.github.com>
Betreff: Re: [hochschule-darmstadt/einander-helfen] Map details button and function (#40)

 

@BernhardHumm <https://github.com/BernhardHumm>  The issue describes the toggle button it is only placed on the right hand side.

What what the x button do? Where is the function of the x button differ to the function of the back button or the function of the toggle button?

**Comment by jschurse** [comment]
Implemented and merged
