### ISSUE TITLE
Search button

### ISSUE THREAD

**Issue by MaiThiD** [hochschule-darmstadt/einander-helfen#42]
**Reason (Why?)**
In order to improve the usability, a search button should be implemented on the homepage. This makes it possible that the user should be able to make his inputs before the search starts. It should also be possible to use the search button without entering parameters, this enables all existing results to be displayed.

**Solution (What?)**
A search button should be implemented. It should called “Suchen” and contains a magnifying glass. Clicking the button leads to the result page and displayed the results with the entered parameters in the homepage.
The user should be able to get all the results by not typing anything and clicking the button. The shape and color of the button should match the current layout. The button’s position should be next to the search bar.

**Not doing**
/

**Relation to other Issues**
None

**Acceptance criteria**
On the homepage is a button implemented with the text “Suchen” and contains a magnifying glass. Clicking the button leads to the result page and displayed the results with the entered parameters in the homepage.
If the user does not enter any parameter and clicked the search button a list of all existing results should be displayed.

**Comment by BernhardHumm** [comment]
The magnifying class logo is enough for the search button (Text “Suchen” not necessary – should be intuitive enough)

 

------------------------------------

 

 

Von: MaiThiD [mailto:notifications@github.com] 
Gesendet: Donnerstag, 18. Juni 2020 21:17
An: hochschule-darmstadt/einander-helfen <einander-helfen@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [hochschule-darmstadt/einander-helfen] Search button (#42)

 

Reason (Why?)
In order to improve the usability, a search button should be implemented on the homepage. This makes it possible that the user should be able to make his inputs before the search starts. It should also be possible to use the search button without entering parameters, this enables all existing results to be displayed.

Solution (What?)
A search button should be implemented. It should called “Suchen” and contains a magnifying glass. Clicking the button leads to the result page and displayed the results with the entered parameters in the homepage.
The user should be able to get all the results by not typing anything and clicking the button. The shape and color of the button should match the current layout. The button’s position should be next to the search bar.

Not doing
/

Relation to other Issues
None

Acceptance criteria
On the homepage is a button implemented with the text “Suchen” and contains a magnifying glass. Clicking the button leads to the result page and displayed the results with the entered parameters in the homepage.
If the user does not enter any parameter and clicked the search button a list of all existing results should be displayed.

**Comment by FiedlerJan** [comment]
Please align the search button on the page 'Home' with the search bar.

**Comment by jschurse** [comment]
fixed by #104
