### ISSUE TITLE
Not all pins are shown on the map

### ISSUE THREAD

**Issue by FiedlerJan** [hochschule-darmstadt/einander-helfen#50]
**Describe the bug**
If the result page is loaded not all loaded posts (100) are displayed on the map with a pin.

**To Reproduce**
1. Go to 'Home'
2. Enter 'Macher/in' in the search bar
3. Click on the proposed tag 'Macher/in'

**Expected behavior**
For each of the loaded posts (100) a pin should be displayed on the map.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/64203299/85153109-0fc93e80-b256-11ea-9057-c2cda1e0c1b8.png)

100 posts are loaded but only 51 are displayed with a pin.

**Desktop (please complete the following information):**
 - Windows 10
 -  Firefox
 -  Version 77

**Smartphone (please complete the following information):**
Not used for testing.

**Additional context**
None

**Comment by jschurse** [comment]
This bug is due to the data we crawl.
Multiple posts reference the same lat/lon pairs.
In your example this would be the following posts for the 50.25/8.9 lat/lon pair

- musikalische Jugendarbeit
- AGO-Engel gesucht
- Aktive für FreuNacht gesucht
- 10.000 Kirchenvorstandmitglieder gesucht

@BernhardHumm How do we want to handle this?
We could minimally change the lat/lon pairs to be unique in a step during our ETL process.

**Comment by BernhardHumm** [comment]
Do not change the lat/lon values for display reasons.

Is there a pin symbol that indicates multiple locations?

 

 

 

------------------------------------

 

 

Von: jschurse [mailto:notifications@github.com] 
Gesendet: Freitag, 19. Juni 2020 20:15
An: hochschule-darmstadt/einander-helfen <einander-helfen@noreply.github.com>
Cc: Humm, Bernhard, Prof. Dr. <bernhard.humm@h-da.de>; Mention <mention@noreply.github.com>
Betreff: Re: [hochschule-darmstadt/einander-helfen] Not all pins are shown on the map (#50)

 

This bug is due to the data we crawl.
Multiple posts reference the same lat/lon pairs.
In your example this would be the following posts for the 50.25/8.9 lat/lon pair

*	musikalische Jugendarbeit
*	AGO-Engel gesucht
*	Aktive für FreuNacht gesucht
*	10.000 Kirchenvorstandmitglieder gesucht

@BernhardHumm <https://github.com/BernhardHumm>  How do we want to handle this?
We could minimally change the lat/lon pairs to be unique in a step during our ETL process.

**Comment by jschurse** [comment]
There is a clustering plugin for leaflet:
https://github.com/Leaflet/Leaflet.markercluster
here is a demo
https://leaflet.github.io/Leaflet.markercluster/example/marker-clustering-realworld.50000.html

**Comment by FiedlerJan** [comment]
> There is a clustering plugin for leaflet:
> https://github.com/Leaflet/Leaflet.markercluster
> here is a demo
> https://leaflet.github.io/Leaflet.markercluster/example/marker-clustering-realworld.50000.html

This would be a nice solution which is also used by https://www.ehrenamtssuche-hessen.de/

**Comment by jschurse** [comment]
fixed by #114
