### ISSUE TITLE
404 page response with 200

### ISSUE THREAD

**Issue by Granoffel** [hochschule-darmstadt/einander-helfen#513]
**Reason (Why?)**
A 404 Page has to response with Status Code 404 Not Found. 

**Solution (What?)**
Change the Status Code from 200 to 404

**Comment by mhendlich** [comment]
This is not really possible to implement since SPAs fully run in the browser and do not act on HTTP status codes after the initial files are loaded. Which is always done before it is known that we are visiting an invalid page.
There seem to be some [hacky workarounds](https://stackoverflow.com/a/54271940) to produce a similar result but I dont think it would be worth to go down that path.
We could technically implement this for only for the case where someone requests an invalid page as their first request, as this could be handled by the web server. But as there is no fix for client-side routing this is inconsistent.

I would close this issue as I also would not prioritize it.

**Comment by Granoffel** [comment]
I used an SEO Checker. The Checker displayed this as a High Issue. But you are probably right.
