### ISSUE TITLE
REST compliant URL for each post

### ISSUE THREAD

**Issue by FiedlerJan** [hochschule-darmstadt/einander-helfen#69]
**Reason (Why?)**
The URLs of einander-helfen.de shall be REST compliant and ther user shall be able to share the link of a post.

**Solution (What?)**
The URL of the result page should be able to take all needed data as an parameter:
* Query
* Location
* Radius

Also the user should be able to copy the link to a post are page of posts and share it in the internet. For this, the id of the post and page index must be present in the URL.

**Not doing**
This issue is focused on the REST compliance of the result page.

**Relation to other Issues**
#54: A resolved bug where the post index was used instead of the post id.

**Acceptance criteria**
The URLs of the result page are REST compliant.

**Comment by jschurse** [comment]
#67 addresses this issue but there is one limitation we should keep in mind.
We currently need the original search parameters to find the post again.
If the user cuts these parameters from the URI we can´t directly adress the post:
e.g.
/posts/8bba27c43f202713c745f2d1704a1725?q=Jugendarbeit&location=&radius=&page=1
will find the post and open it
/posts/8bba27c43f202713c745f2d1704a1725
won´t find the post.

This is due to the fact that we have no page for one single post but display it in the page with the search results.

**Comment by FiedlerJan** [comment]
I think that should be covered by a separate issue.

The issue will be linked here in the comments once it has been created.
