### ISSUE TITLE
Currently only the 100 first posts are being shown

### ISSUE THREAD

**Issue by jschurse** [hochschule-darmstadt/einander-helfen#88]
**Describe the bug**
On the resultpage currently only the 100 first posts are being shown.
If there are more results the user has no way of retrieving them.

**To Reproduce**
1. Go to https://cai-einander-helfen-staging.fbi.h-da.de/posts?q=&location=&radius=&page=1
2. See only seven available pages :(

**Expected behavior**
The pagination should contain pages for all results.
If user enters a page where no results are available load the corresponding results.

**Additional context**
We cannot just implement a fetch for each page individually, sice then only the posts on the current displayed page are being shown on the map.
To be able to display more markers on the map we need bigger result sets.

**Considered Alternatives**
Maybe we should kick the concept of 'pages' and just do an infinite scroll?
This would enable us to load results easily on demand but will aggravate the issue described here https://github.com/hochschule-darmstadt/einander-helfen/issues/69#issuecomment-647650386

**Comment by FiedlerJan** [comment]
> If the user clicks on a page which is not already loaded, the selected page should be loaded and the loaded results should be additionally displayed on the map. The pagination should contain as many pages as it needs to display all possible posts.

This bug links to the issue #43.

**Comment by BernhardHumm** [comment]
We already talked about the issue with markers at large result sets:

Add markers continuously when user selects additional pages.

 

If there should be a performance issue then we have to think about alternatives.

 

 

 

------------------------------------

 

 

Von: Jenja Schurse [mailto:notifications@github.com] 
Gesendet: Donnerstag, 25. Juni 2020 13:38
An: hochschule-darmstadt/einander-helfen <einander-helfen@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [hochschule-darmstadt/einander-helfen] Currently only the 100 first posts are being shown (#88)

 

Describe the bug
On the resultpage currently only the 100 first posts are being shown.
If there are more results the user has no way of retrieving them.

To Reproduce

1.	Go to https://cai-einander-helfen-staging.fbi.h-da.de/posts?q= <https://cai-einander-helfen-staging.fbi.h-da.de/posts?q=&location=&radius=&page=1> &location=&radius=&page=1
2.	See only seven available pages :(

Expected behavior
The pagination should contain pages for all results.
If user enters a page where no results are available load the corresponding results.

Additional context
We cannot just implement a fetch for each page individually, sice then only the posts on the current displayed page are being shown on the map.
To be able to display more markers on the map we need bigger result sets.

Considered Alternatives
Maybe we should kick the concept of 'pages' and just do an infinite scroll?
This would enable us to load results easily on demand but will aggravate the issue described here #69 (comment) <https://github.com/hochschule-darmstadt/einander-helfen/issues/69#issuecomment-647650386>
